# Generated by Django 5.2.4 on 2025-07-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('moderator', 'Moderator'), ('user', 'User'), ('admin', 'Admin')], default='guest', max_length=10),
        ),
    ]
